compositionIdentifier: crossplane.jamf.com
provider:
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
  name: provider-aws
  version: v0.40.0
labels:
  fromCRD:
    - controlling.crossplane.jamf.com/cost-reference
    - controlling.crossplane.jamf.com/owner
    - controlling.crossplane.jamf.com/product
    - tags.crossplane.jamf.com/account
    - tags.crossplane.jamf.com/cluster
    - tags.crossplane.jamf.com/environment
    - tags.crossplane.jamf.com/namespace
    - tags.crossplane.jamf.com/team
  common:
    tags.crossplane.jamf.com/project: kubernetes
    tags.crossplane.jamf.com/owner: chaosmonkeys
tags:
  fromLabels:
    - tags.crossplane.jamf.com/account
    - tags.crossplane.jamf.com/cluster
    - tags.crossplane.jamf.com/environment
    - tags.crossplane.jamf.com/namespace
    - tags.crossplane.jamf.com/team
  common:
    project: kubernetes
    owner: chaosmonkeys